language: node_js
node_js:
- '6'
- node
sudo: required
services:
- docker
before_install:
- npm link
- npm install -g npm@'>=2.13.5'
- docker pull rabbitmq:3-management
- docker run -d -p 5671:5671 -p 15672:15672 -p 5672:5672 rabbitmq:3-management
script: npm run build-test
notifications:
  slack:
    secure: Qk4sUUQSQ/hFlANo40SC0S4fOvEIdJ2wBEzOm17QzyPFBLPzcGorFJcNVaJcBQ18qWn64RMi2ona+00PtTSOUBb/xNeHLvE/NC4Qyu0SDHNmsNV/0DJ7ODJlqAHL1OVjfhMDsngLKSJSTmudeXPTCFrNGh4yeNX9qkfnobK/xhJxSpCPVdR6wHHmgjwEQ5WDQGGGpvYKBCrD8a0+ko2/WOjdjFUVBEEAqdBVBdF9E4zFn6A1Mp5baxy3SNzfTuSS/usxq5Ayd6qnYITv7CvxqCsH/4mGyrWgTD0OJCXamDWGJFM1dbhOsGN4rT3w6fcwErObjEJwjPT1bnNZyMvafUgYufroE2dMhl13vziTWbZ4cYHpc1FHbcuKCeHJKNWZQMSe70xf5DZINUHB0yug25OqOIQrFglzlWSdz7ro0XCmBSa88U5aVjWLXeX8ZV7PjuteQmJ0PI8/ROKA/XNyji96lScSteuY+sURgh/8CASXDL/7+YEiJO8HzN85XlbDwPuNQWApBhyW04DQbe8P7TjCv/y9lvGZ71RqaSDmYXs/dd3jh+JK3m3+wY1lt6DpTXUWdOuFQEJwV3QkTBG0Gb1aI+86IVRisAvkSa1+hC9xSEs44volv00pWemaAsiG4HnQha/lKh6e8kwIy2ac1SE1oKzVrTCoPMrWIhjuClo=
deploy:
  provider: npm
  email: xo-npmjs.group@xogrp.com
  api_key:
    secure: l7BCG6sPFusLj6g+KsDRraHvrBRb5Bzwmeddv5OKs+2iEa/FYP9p176wO9ChTb68ceEFNj7QHW2niFEvshRLOTC4QFVGv//ExI70oq0ZSGHYhEBnoBR4dFtaf+ad0VB+wmIFSMMX7hEtddu0nb4j2CD8ng/4TXetH3YABrl+3CKLHiCNc2o2IyPp50GKYj7E79DIuI502bJBlrzxyNOJPbQSQOMvKwpHdO+7c6hRdhAI99NXsmn3nyPsLiED3EU4kSYyW+xKcSZnuTwhXB1itddHDymO3t+Tw+BOISEImIVHIjNgcgQiYaoi9z3alYqCrZHl/FZrqwNsi1yqF0AoP40wKpLxyVkimkes/wXbUI4Y09THwnqLZ+bl5H+7mw7Debj33EmXNXVYBG16Hip/aTxvm+lfwxo7mbQc+8aude+zJ/eUq/gnmlGg8cvyBl5+Ood+TSjTvoMgvQ4E4wHKQzuQ3ZSsBjpaB7s6rXhXYFQl7xFnwWSR6HfyPjiNeMAMerXLXAwUqhKVdC90DsICdj45Nrih2Q4SgJ6Tq7XDh+6/Kp3eVWsQSr61ur+66eE0DZJZDZImQpJml+HFqF/1cxa8tRNlDWSaSVhLWuFc/69B18DEYs24LnK3+5NgHq+KLZUZT6Xm1fJXzgtLppjZsmUNwwJEPbz5m7bYSd3jgEs=
  on:
    tags: true
    repo: xogroup/bunnybus-cli
